apps/app_reglogin/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name ='my_index'),
    url(r'^register$', views.registration ,name ='my_register'),
    url(r'^login$', views.loginuser, name ='my_loginuser')]
     

travelbuddy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^travels/', include('apps.app_travel.urls',namespace='travels')) ,
    url(r'^', include('apps.app_reglogin.urls',namespace='users')) 
]

apps/app_reglogin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import bcrypt
 
class UserManager(models.Manager):
    def register(self, postData):
        print postData
        results = {'status': True, 'errors': [],'user':None}
        if not postData['name'] or len(postData['name']) <1:
            print "name error"
            results['status'] = False
            results['errors'].append("Please enter name")

        elif len(postData['name']) <3:
            print "name length error"
            results['status'] = False
            results['errors'].append("Name should be atleast three characters long")

         

        if not postData['username'] or len(postData['username']) <1:
            results['status'] = False
            results['errors'].append("Please enter Username")
        
        elif not postData['username'] or len(postData['username']) <3:
            results['status'] = False
            results['errors'].append("UserName should be atleast three characters long")

        if not postData['password'] or len(postData['password']) <8:
            results['status'] = False
            results['errors'].append("Password must be atleast 8 characters long")
        
        elif not postData['confirmpassword'] or len(postData['confirmpassword']) <1:
            results['status'] = False
            results['errors'].append("Please enter password in Confirm PW")
        
        if postData['confirmpassword'] != postData['password']:
            results['status'] = False
            results['errors'].append("Passwords do not match")

        if not results['status']:
            return results
       
        x = User.objects.filter(username = postData['username'])

        try:
            if x[0]:
                results['errors'].append("User already exists")
                results['status'] = False
        except:
            if results['status']:
                password = postData['password'].encode() # to get from unicode to string
                hashed = bcrypt.hashpw(password, bcrypt.gensalt())
                print hashed
                y = User.objects.create(name=postData['name'], username=postData['username'], password=hashed)
                y.save()
                results['user'] = y
        return results

    def loginval(self, postData):
        results = {'status': True, 'errors': [],'user':None}

        print postData
        if not postData['username'] or len(postData['username']) <1:
            results['status'] = False
            results['errors'].append("Please enter Username")
        
        elif not postData['username'] or len(postData['username']) <3:
            results['status'] = False
            results['errors'].append("UserName should be atleast three characters long")

        if not postData['password'] or len(postData['password']) <1:
            results['status'] = False
            results['errors'].append("Please enter Password")

        elif not postData['password'] or len(postData['password']) <8:
            results['status'] = False
            results['errors'].append("Password must be atleast 8 characters long")
        
        if results['status'] == True:
            x = User.objects.filter(username = postData['username'])
        #print x
        
            try:
                if x[0]:
                    print "password testing"
                    password = postData['password'].encode()
                    y = x[0].password.encode()
                    if bcrypt.hashpw(password,y) == y:
                        results['status'] = True
                        print ("*****It matches**********")
                        results['user'] = x[0]
                    else:
                        results['status'] =False
                        results['errors'].append("Invalid credentials")
 
            except:
                results['status'] =False
                print "please regitser"
                results['errors'].append("Please Register")
        return results

        


class User(models.Model):
    name = models.CharField(max_length=38)
    username = models.CharField(max_length=38)
    password = models.CharField(max_length=38)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()
    #tripusers

apps/app_reglogin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User 
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    #User.objects.all().delete()
 
    return render(request,'app_reglogin/index.html' )

def registration(request):
    result = User.objects.register(request.POST)
    if not result['status']:
        for error in result['errors']:
            messages.error(request,error)
        return redirect(reverse('users:my_index'))
    else:
        messages.success(request,"Successful")
        request.session['userid'] = result['user'].id         
        request.session['username'] = result['user'].username
        request.session['name'] = result['user'].name
        return redirect(reverse('travels:home_page'))
 
def loginuser(request):
    result = User.objects.loginval(request.POST)
    
    if not result['status']:
        for error in result['errors']:
            messages.error(request,error)
        return redirect(reverse('users:my_index'))
    else:
        messages.success(request,"Successful")
        request.session['userid'] = result['user'].id
        request.session['username'] = result['user'].username
        request.session['name'] = result['user'].name
        return redirect(reverse('travels:home_page'))

apps/app_reglogin/templates/app_reglogin/index.html
<html>
    <head>
       <title>Registration Form</title>
          {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_reglogin/stylesheets/loginregstyle.css' %}">
   
    </head>
    <body>
        <div id="error">
      {% for user in users %}
            {{user.first_name}},{{user.last_name}},{{user.emailid}},{{user.password}},{{user.id}}
        {% endfor %}
        
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
             
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        </div>
        <h1>Welcome!</p>
      <h1>Registration </h1>

        <div id="reg">
        <form action="{% url 'users:my_register'%}" method ="post">
        {% csrf_token %}
        <p>
        <label for="first_name">Name:</label>
        
        <input type="text" id ="name" name="name">
        </p>
        <p>
        <label for="last_name">Username:</label>
        <input type="text" id ="username" name="username">
        </p>
        <p>
        <label for="password">Password:</label>
        <input type="password" id ="password" name="password">
        </p>
        <p>
        <label for="confirmpassword">Confirm PW:</label>
        <input type="password" id ="confirmpassword" name="confirmpassword">
        </p><p>
        <input type = "hidden" name = "action" value="Register">
        <input id="submits" type="submit" value="Register">
        </form>
        </div>
        <div id="login">
        <h1> Login </h1>
        <form action="{% url 'users:my_loginuser'%}"  method ="post">
        {% csrf_token %}
            <p>
            <label for="username">Username:</label>
            <input type="text" id ="username" name="username"
            </p><p>
            <label for="password">Password:</label>
            <input type="password" id ="password" name="password"
            </p><p>
            <input type = "hidden" name = "action" value="Login">
            <input id="submits"   type="submit" value="Login">
            </p>
        </form>
        </div>


    </body>
</html>