apps/app_travel/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
    url(r'^homepage$', views.homepage , name ='home_page'),
    url(r'^destination/(?P<id>\d+)$', views.destination , name ='destination') ,
     url(r'^addlike/(?P<id>\d+)$', views.addlike , name ='addlike') ,
    url(r'^logout$', views.logout , name ='logout') ,
    url(r'^add$', views.addtravelplan , name ='add_travelplan')
    ]
     

travelbuddy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^travels/', include('apps.app_travel.urls',namespace='travels')) ,
    url(r'^', include('apps.app_reglogin.urls',namespace='users')) 
]

apps/app_travel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..app_reglogin.models import User
from django.db import models
from datetime import date
from datetime import datetime
import time 
import bcrypt
 
class tripscheduleManager(models.Manager):
    def addtravelplan(request,postData,sessiondata):
        print postData
        print " In addtravelplan %%%%%%%%%%%"
        
        results = {'status': True, 'errors': []}
        if not postData['destination'] or len(postData['destination'])<1:
            print "In destination "
            results['status'] = False
            results['errors'].append("Please enter a destination")

        if not postData['description'] or len(postData['description'])<1:
            print "In description "
            results['status'] = False
            results['errors'].append("Please enter a description")

        if not postData['plan'] or len(postData['plan'])<1:
            print "In plan "
            results['status'] = False
            results['errors'].append("Please enter a plan")
        
        if not postData['startdate'] or len(postData['startdate'])<1:
            print "In startdate "
            results['status'] = False
            results['errors'].append("Please enter a Travel Date From")



        if not postData['returndate'] or len(postData['returndate'])<1:
            print "In returndate "
            results['status'] = False
            results['errors'].append("Please enter a Travel Date To")

        if results['status']:   
            today = datetime.now().date()
            start = datetime.strptime(postData['startdate'], '%Y-%m-%d').date()
            end = datetime.strptime(postData['returndate'], '%Y-%m-%d').date()
       
            if start < today:  
                results['status'] = False
                results['errors'].append('Travel Date From must be in the future.')
            if end < today:
                results['status'] = False
                results['errors'].append('Travel Date To must be in the future.')
            # #validate date to not before date from
            if end < start:
                results['status'] = False
                results['errors'].append('Travel Date To is before Travel Date From')

        if results['status']:
            user1 = User.objects.get(id = sessiondata['userid'])
            Travelplan1 = Tripschedule.objects.create(destination=postData['destination'],
            tripdesc=postData['description'],plan=postData['plan'],
            startdate=postData['startdate'],
            returndate=postData['returndate'],tripuser = user1)
        
          
            results['status'] = True
            print "Successfully done!!!!!!!!!"
       
        return results            

    def addlike(request,context):
        print context
        results = {'status': True, 'errors': []}

        trip1=Tripschedule.objects.get(id=context["tripid"])
        user1=User.objects.get(id=context["userid"])
        if trip1.tripuser == user1:
            print "In validation1 "
            results['status'] = False
            results['errors'].append("You cannot join your own trip!")
        else:
            trip1.joinpeople.add(user1)
            print "join done!!!!!!!!!"
            results['status'] = True
        return results 


class Tripschedule(models.Model):
    destination = models.TextField(max_length=1000)
    tripdesc = models.TextField(max_length=1000)
    plan=models.TextField(max_length=1000)
    startdate = models.DateField()
    returndate = models.DateField()
    tripuser= models.ForeignKey('app_reglogin.User', related_name="tripusers")
    joinpeople = models.ManyToManyField('app_reglogin.User', related_name="joinpeoples")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
     
    objects=tripscheduleManager()
    #bookauthors
    #bookreviews
 
    

apps/app_travel/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from ..app_reglogin.models import User
from .models import Tripschedule
from django.core.urlresolvers import reverse

# Create your views here.
def homepage(request):
    #Tripschedule.objects.all().delete()
    context = {
                    'Tripscheduledata' :  Tripschedule.objects.all(),
                    "name": request.session['name'],             
                    "userid" :  request.session['userid'] 
                }
   
    return render(request,'app_travel/homepage.html', context)


def addtravelplan(request):

    if request.method == "POST":
        print request.POST
        context = {
                "name": request.session['name'],
                "userid" :  request.session['userid'] 
                }
      
        result = Tripschedule.objects.addtravelplan(request.POST,context)
        print  result['status']
        if not result['status']:
             
            for error in result['errors']:
                messages.error(request,error)
                print "here"
            return redirect(reverse('travels:add_travelplan'))
        else: 
            messages.success(request,"Successful")
            return redirect(reverse('travels:home_page'))
            
    else:
            print "ENTERED GET"
            context = {
                    'Tripscheduledata' :  Tripschedule.objects.all(),
                    "name": request.session['name']    
             }
    return render(request,'app_travel/addtravelplan.html',context )


def destination(request,id):
 
    context = {
        "name": request.session['name'],
        'trip' :Tripschedule.objects.get(id=id)
        }
     
        #return redirect(reverse('show',kwargs={'id':id}))
    return render(request,'app_travel/destination.html', context)



def addlike(request,id):    
    context = {
                "tripid" :id,
                "userid" :  request.session['userid'] ,
                "name": request.session['name']
                }
    result = Tripschedule.objects.addlike(context)
    if not result['status']:
            for error in result['errors']:
                messages.error(request,error)
                print "here"
            #return redirect(reverse('secrets:add_like',kwargs={'id': id}))
            return redirect(reverse('travels:home_page'))
    else: 
            messages.success(request,"Successful")
            return redirect(reverse('travels:home_page'))


def logout(request):
    request.session.clear()
    return redirect('users:my_index')

apps/app_travel/templates/app_travel/addtravelplan.html
<html>
    <head>
       <title>Add Travel Plan</title>
                 {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_travel/style/style.css' %}">
    </head>
    <body>
    <p>
     <a href = {% url 'travels:home_page'%} >Home</a>
     <a href = {% url 'travels:logout'%}>Logout</a>
    </p>
       <div id ="error" >
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
             
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
       </div> 
    <h1>Add a Trip</h1>

     <form action="{% url 'travels:add_travelplan'%}" method ="post">
        {% csrf_token %}
        <p>
        <label for="destination">Destination:</label>
        <input type="text" id ="destination" name="destination">
        </p>
        <p>
        <label for="description">Description:</label>
        <input type="text" id ="description" name="description">
        </p>
        <p>
        <label for="plan">Plan:</label>
        <input type="text" id ="plan" name="plan">
        </p>
        <p>
        <label for="startdate">Travel Date From:</label>
        <input type="date" id ="startdate" name="startdate">
        </p>
        <p>
        <label for="returndate">Travel Date To:</label>
        <input type="date" id ="enddate" name="returndate">
        </p>
        <p><input id="submits" type="submit" value="Add"></p>
        </form>

apps/app_travel/templates/app_travel/destination.html
<!DOCTYPE html>
<html>
    <head>
       <title>Travel Dashboard</title>
                 {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_travel/style/style.css' %}">
    </head>
    <body>
     <a href = {% url 'travels:home_page'%} >Home</a>
     <a href = {% url 'travels:logout'%}>Logout</a>
 {{context}}
        <h1> {{trip.destination}}</h1>
            <p> Planned By : {{trip.tripuser.name}}</p>
            <p> Description : {{trip.tripdesc}}</p>
            <p> Travel Date From : {{trip.startdate}}</p>
            <p> Travel Date To :{{trip.returndate}}</p>
           
        <h1> Other User's joining the trip</h1>

             {%for jointrip in trip.joinpeople.all %}
                    <p><strong>{{jointrip.name}}</strong><p>
                        
             {% endfor %}
              <p>{{name}}</p>

             

apps/app_travel/templates/app_travel/homepage.html
<!DOCTYPE html>
<html>
    <head>
       <title>Travel Dashboard</title>
                 {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_travel/style/style.css' %}">
        
   
    </head>
    <body>
         <div id ="error" >
                {% if messages %}
            <ul class="messages">
                {% for message in messages %}
             
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
         </div>
        <p>
      <h1>Hello {{name}}!</h1>
      <a href = {% url 'travels:logout'%}>Logout</a>

      <h4> Your Trip Schedules</h4>
      <table style="width:50%">
            <tr>
                <th>Destination</th>
                <th>Travel Start Date </th>
                <th>Travel End Date </th>
                <th>Plan </th>
            </tr>
           
            {% for trip in Tripscheduledata %}
                {% if trip.tripuser.id == userid %}
                <tr>
                     
                        <td><a href={% url 'travels:destination' trip.id %} target="_blank">{{trip.destination}}</td>
                        <td>{{trip.startdate}}</td>
                        <td>{{trip.returndate}}</td>
                        <td>{{trip.plan}}</td>
                     </tr> 
                {%endif%}
            {% endfor %}
          
        </table>  

      <h4> Other User's Travel Plans</h4>
      <table style="width:50%">
            <tr>
                <th>Name</th>
                <th>Destination</th>
                <th>Travel Start Date </th>
                <th>Travel End Date </th>
                <th>Plan </th>
                <th>Do You Want to Join? </th>
            </tr>
           
            {% for trip in Tripscheduledata %}
                {% if trip.tripuser.id != userid %}
                <tr>
                        <td>{{trip.tripuser.name}}</td>
                        <td><a href={% url 'travels:destination' trip.id %} target="_blank">{{trip.destination}}</td>
                        <td>{{trip.startdate}}</td>
                        <td>{{trip.returndate}}</td>
                        <td>{{trip.plan}}</td>
                        <td><a href = {% url 'travels:addlike' trip.id%}>Join</a> </p>
                     </tr> 
                {%endif%}
            {% endfor %}
          
        </table>  

        <a href = {% url 'travels:add_travelplan'%}>Add Travel Plan</a>
           